# Generated by Django 5.1.5 on 2025-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
