# Generated by Django 5.1.5 on 2025-05-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference_number',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
